## 1 Carga del dataset pre procesado
* Modulo scraper que entrega autos_autocosmos.csv sin nulos ni valores duplicados luego de realizar webscraping en autocosmos.com.ar 
* El modulo conversor carga el dataset entregado por el scraper, dolariza todos los precios mediante la funcion conversor que llama la API para obtener el valor del dolar al dia.

In [306]:
import sys
sys.path.append("..")

import pandas as pd
from config import RAW_DATA_PATH
from conversor import procesar_dataset 

df = procesar_dataset()
df.info()

Dólar blue a la fecha: 1550
✅ Archivo CSV dolarizado guardado en G:\Mi unidad\Price_pred\data\processed\autos_dolarizado.csv
<class 'pandas.DataFrame'>
RangeIndex: 4714 entries, 0 to 4713
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   marca       4714 non-null   str
 1   modelo      4714 non-null   str
 2   anio        4714 non-null   int64
 3   km          4714 non-null   int64
 4   ciudad      4714 non-null   str
 5   provincia   4714 non-null   str
 6   precio_usd  4714 non-null   float64
dtypes: float64(1), int64(2), str(4)
memory usage: 257.9 KB

## 2 Diagnóstico inicial 
### Variables cuantitativas, nulos, duplicados, rango de valores plausibles:

A verificar posibles errores y otliers:

* ¿Existen registros con 'km' = 0, pero años que no cohincide? 
* ¿Existen registros con 'anio' muy antiguo, de que tipo de vehiculo se trata?

In [307]:
df.head()

,marca,modelo,anio,km,ciudad,provincia,precio_usd
0,Chevrolet,Onix,2018,73000,Hurlingham,Buenos Aires (A.M.B.A.),6451.612903
1,Chevrolet,Cruze 5,2023,102000,Saavedra,Ciudad Autónoma Buenos Aires,16129.032258
2,Citroën,Berlingo Multispace,2017,84000,Flores,Ciudad Autónoma Buenos Aires,10903.225806
3,Renault,Kangoo,2014,84004,Flores,Ciudad Autónoma Buenos Aires,8322.580645
4,Volkswagen,Gol Trend,2020,20000,Flores,Ciudad Autónoma Buenos Aires,1290.321935

In [308]:
df['anio'].max() # existe el año 2027

df = df[df['anio'] != 2027]

# elimino los registros donde el valor es un error

### Histograma de valores en kilometraje 'km'

Cómo esta compuesto este campo? que valor predominan con respecto a la antiguedad/uso de los vehiculo que se ofrecen.

Verifiqué los registros con valores elevados o atípicos (mucho km y poca antiguedad o viseversa), para clasificar el caso, o verificar y corregir errores de carga.

In [309]:
import plotly.express as px

hist = px.histogram(df,
                    x = "km",
                    nbins=100,
                    title="Distribucion de kilometrajes",
                    template = 'plotly_dark',
                    height = 400,
                    width = 600).show()

### Verificacion de casos con bajo km, se verifica si es posible o realista en relacion al valor de 'anio', y km=100 (caso de placeholder)

In [310]:
km_100 = df[df['km'] == 100].index
df = df.drop(km_100)

Verificado que km = 1 y 0, tienen un precio acorde a un auto 0km. Los conservo porque son parte del mercado actual

FIAT Cronos, FIAT Pulse, FIAT Argo, FIAT Fastback, y Chevrolet Onix/Tracker. Acá el precio está objetivamente mal.
km=21 repetido idéntico en 6 filas de Cronos
km=300 repetido en Onix/Tracker/Onix/Cronos/Tracker
un valor fijo reapareciendo en modelos y marcas distintas, otra vez la firma de un valor de fallback/cuota mal 
capturado por el scraper en vez del precio y/o km real

In [311]:
km_300 = df[df['km'] == 300]
km_21 = df[df['km'] == 21]

# elimino los registros donde km =21, 300
df = df[~df['km'].isin([21, 300])]

In [312]:
km_bajos = df[(df['km'] < 1000) & (df['anio']< 2025)].index

df.drop(km_bajos, inplace = True)

In [313]:
precios_altos = df[df['precio_usd']>800000].index
df.drop(precios_altos, inplace=True)

### Grafico de scatter - antiguedad del vehiculo y el kilometraje declarado

Busco verificar la coherencia en general, que los vehiculos con mayor antiguedad tengan un km mas alto, y viceversa, y en caso contrario, verificar la veracidad o tratar ese dato erroneo.

Se obeserva una nube de datos donde las relaciones parecen coherentes, y dos clusteres dispersos, donde por un lado se encuentran vehiculos antiguos con baja cantidad de kilometraje, candidatos a 'Coleccion' y vehiculos con pocos años de antiguedad pero muchos kilometros acumulados (se chequean los precios)

In [314]:
scatter = px.scatter(df,
                     x = 'anio',
                     y = 'km',
                     template = 'plotly_dark',
                     hover_data = ['modelo', 'precio_usd'],
                     ).show()

In [315]:
# deteccion y verificacion de outliers o posibles categorias
autos_antiguos_coleccion = df[(df['km'] < 3000) & (df['anio']< 2000)]

# categoria creada luego de verificar los datos 
df.loc[[1428, 1748, 3627, 3990, 4010], 'categoria'] = 'coleccion'

display(autos_antiguos_coleccion)

,marca,modelo,anio,km,ciudad,provincia,precio_usd
1428,Daihatsu,Cuore,1994,1000,Vistalba,Mendoza,50322.580645
1748,Ford,T,1929,1000,Las Heras,Mendoza,19500.000000
3627,FIAT,600,1962,1000,Campana,Buenos Aires,10000.000000
3990,Ford,Falcon,1980,1000,Coronel Brandsen,Buenos Aires,3096.774194
4010,Ika,Estanciera,1970,1100,La Falda,Córdoba,10967.741935

In [316]:
# agrupar categorias generales (coleccion, pickup, sedan etc)
import pandas as pd
modelos_unicos = df[['marca', 'modelo']].drop_duplicates().sort_values(['marca', 'modelo'])

print(modelos_unicos.shape)

modelos_unicos.to_csv(r"G:\Mi unidad\Price_pred\notebooks\modelos_para_categorizar.csv", index=False)

(421, 2)

In [317]:
# A partir de este csv clasifico por tipo de vehiculo para obtener mas informacion util para el modelo
# sin tener que lidiar con las 421 modelos que aportan mas ruido que datos utiles para este caso
# categorizacion con Claude
modelos_unicos

           marca        modelo
1097      Agrale        Marruá
1571  Alfa Romeo          MiTo
2615  Alfa Romeo       Stelvio
1027        Audi            A1
302         Audi  A1 Sportback
...          ...           ...
341        Volvo           V70
3497       Volvo          XC60
326      Zanella   Force Truck
3044       smart       Forfour
261        smart        Fortwo

[421 rows x 2 columns]

In [318]:
categorias = pd.read_csv(r"G:\Mi unidad\Price_pred\notebooks\modelos_categorizados.csv")
df = df.merge(categorias, on=["marca", "modelo"], how="left")
df.drop(columns = ['categoria','modelo'], inplace = True)

In [319]:
df.head()

,marca,anio,km,ciudad,provincia,precio_usd,carroceria
0,Chevrolet,2018,73000,Hurlingham,Buenos Aires (A.M.B.A.),6451.612903,Hatchback
1,Chevrolet,2023,102000,Saavedra,Ciudad Autónoma Buenos Aires,16129.032258,Hatchback
2,Citroën,2017,84000,Flores,Ciudad Autónoma Buenos Aires,10903.225806,Minivan
3,Renault,2014,84004,Flores,Ciudad Autónoma Buenos Aires,8322.580645,Furgón
4,Volkswagen,2020,20000,Flores,Ciudad Autónoma Buenos Aires,1290.321935,Hatchback

In [320]:
out = df[(df['precio_usd'] > 80000)]

out

,marca,anio,km,ciudad,provincia,precio_usd,carroceria
254,FIAT,2006,300000,La Falda,Córdoba,258064.516129,Sedán
668,Citroën,2023,40000,Colegiales,Ciudad Autónoma Buenos Aires,132258.064516,Hatchback
1694,Mercedes,2021,27000,Villa Urquiza,Ciudad Autónoma Buenos Aires,96900.000000,SUV
1700,Audi,2021,27000,Villa Urquiza,Ciudad Autónoma Buenos Aires,99000.000000,SUV
2438,Porsche,2011,74000,Guaymallén,Mendoza,95000.000000,Sedán
3009,Ford,2025,12000,Rosario,Santa Fe,110000.000000,Pickup
3138,Volkswagen,2024,10000,Puerto Madero,Ciudad Autónoma Buenos Aires,225806.451613,Pickup
3749,Honda,2009,170000,Wilde,Buenos Aires (A.M.B.A.),110000.000000,Hatchback
4503,Honda,2019,126000,Bahía Blanca,Buenos Aires,240000.000000,SUV

In [321]:
df = df.drop(index=out.index)

In [322]:
hist = px.histogram(df,
                    x = 'carroceria',
                    template = 'plotly_dark',
                    title = 'Conteo de carroceria'
                    )
hist.show()

In [323]:
mediana_precio_carr = df.groupby('carroceria')['precio_usd'].median()
mediana_precio_carr

carroceria
Cabriolet     10750.000000
Camión        18500.000000
Clásico        3685.483871
Coupé         23000.000000
Furgón        10000.000000
Hatchback      8508.064516
Minivan        8508.064516
Pickup        19032.258065
SUV           14838.709677
Sedán         10967.741935
Utilitario    54750.000000
Wagon          7096.774194
Name: precio_usd, dtype: float64

### Box plot de valores de vehiculos por año (antiguedad) 
Se marcan los 'suspected outliers' y se verifica que estos son modelos de autos cuyo valor atipico esta justificado (Audi Q8, Mercedes, Camaro, etc vehiculos conocidamente caros)

podemos observar los casos de coleccion con precios mas elevados en años sub 1990, observamos como la media de precio sube a medida que aumenta 'anio', vehiculos mas nuevos, lo que es esperable, los outliers estan verificados y son veraces.

In [324]:
plot = px.box(df,
              x = 'anio',
              y = 'precio_usd',
              points = 'suspectedoutliers',
              template = 'plotly_dark',
              hover_data= ['marca','carroceria'],
              title = 'Evoucion de precios por antiguedad'
              ).show()

In [325]:
# Outliers de precio — AMBOS extremos (bajo Y alto)
# outlier detectado en el grafico de 1.22M Fiar Chronos se lo considera error de carga

df['precio_usd'] = df['precio_usd'].round(2)

outliers_precio = df[(df['precio_usd'] < 1000) | (df['precio_usd'] > 120000)].index

#outliers_precio 

df = df.drop(outliers_precio)

In [326]:
df = df.drop(index= [2473, 1713,3051])

In [327]:
# verifico la veracidad de los registros con menos de 1000 km
error = df[df['km'] < 1000]
error.count()
error

,marca,anio,km,ciudad,provincia,precio_usd,carroceria
216,Peugeot,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,23548.39,SUV
231,Chery,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,29000.00,SUV
301,Citroën,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,17419.35,SUV
388,BAIC,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,34000.00,SUV
390,Chery,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,29500.00,SUV
446,BAIC,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,31000.00,SUV
549,Peugeot,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,31683.10,Furgón
567,Peugeot,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,40455.48,SUV
751,Peugeot,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,22322.58,Hatchback
754,Volkswagen,2026,1,Posadas,Misiones,19258.06,Hatchback
824,Citroën,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,18709.68,SUV
915,Peugeot,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,22129.03,SUV
1011,FIAT,2025,10,General Pacheco,Buenos Aires (A.M.B.A.),17161.29,Furgón
1143,FIAT,2026,1,El Talar,Buenos Aires (A.M.B.A.),19354.84,Pickup
1146,Nissan,2026,1,Posadas,Misiones,34264.90,SUV
1324,Peugeot,2026,1,Caballito,Ciudad Autónoma Buenos Aires,6129.03,Furgón
1438,Toyota,2025,700,Mar del Plata,Buenos Aires,51612.90,Pickup
1635,FIAT,2025,31,Córdoba,Córdoba,26428.39,SUV
1658,Renault,2026,1,Córdoba,Córdoba,25161.29,SUV
1897,Volkswagen,2026,500,San Isidro,Buenos Aires (A.M.B.A.),28500.00,SUV
2217,Citroën,2026,10,San Andres,Buenos Aires (A.M.B.A.),16322.58,Hatchback
2271,Renault,2026,9,Córdoba,Córdoba,33548.39,Pickup
2351,Volkswagen,2026,1,Neuquén,Neuquén,33483.87,SUV
2398,Peugeot,2026,1,Neuquén,Neuquén,29032.26,SUV
2507,Chevrolet,2025,1,Neuquén,Neuquén,30967.74,SUV
2550,Citroën,2025,1,Neuquén,Neuquén,21290.32,SUV
2582,Ford,2026,1,Neuquén,Neuquén,36064.52,SUV
2941,Peugeot,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,19935.48,Furgón
2996,Peugeot,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,21290.32,Hatchback
3080,Haval,2025,1,Córdoba,Córdoba,35500.00,SUV
3188,Great Wall,2025,1,Córdoba,Córdoba,32990.00,SUV
3190,Jeep,2025,1,Ituzaingo,Buenos Aires (A.M.B.A.),21612.90,SUV
3392,Peugeot,2026,1,Colegiales,Ciudad Autónoma Buenos Aires,25741.94,SUV
3400,Ford,2025,1,Neuquén,Neuquén,31548.39,SUV
3453,Renault,2025,10,Neuquén,Neuquén,18645.16,Sedán
3582,Renault,2025,705,La Calera,Córdoba,12903.23,Hatchback
3734,Volkswagen,2025,17,Ramos Mejia,Buenos Aires (A.M.B.A.),32000.00,SUV
4198,FIAT,2025,1,Pilar,Buenos Aires (A.M.B.A.),9032.26,SUV
4203,FIAT,2025,1,Pilar,Buenos Aires (A.M.B.A.),4606.45,Hatchback
4235,FIAT,2025,1,Garin,Buenos Aires (A.M.B.A.),5806.45,SUV
4275,FIAT,2025,1,José C. Paz,Buenos Aires (A.M.B.A.),5805.81,SUV
4472,Peugeot,2025,15,Caballito,Ciudad Autónoma Buenos Aires,3870.97,Furgón
4600,Ford,2025,969,Rosario,Santa Fe,39500.00,SUV

In [328]:
df.drop(index=[4198, 4203, 4235, 4275, 4472], inplace=True)

### Histograma de precios, luego de tratar los autliers de km

In [329]:
hist = px.histogram(df,
                    x = "precio_usd",
                    nbins=100,
                    title="Distribucion de precios",
                    template = 'plotly_dark',
                    height = 400,
                    width = 600).show()

### Verifico km en relacion a precio_usd, de los vehiculos de año menor a 1980

Tomo la lista y verifico con Claude la veracidad de los registros

In [330]:
#limpio ✅
outliers_km = df[(df['anio'] < 1980)]
outliers_km

,marca,anio,km,ciudad,provincia,precio_usd,carroceria
459,Chevrolet,1960,6000,San Martin,Buenos Aires (A.M.B.A.),14000.00,Pickup
844,Jeep,1963,99998,Ferré,Buenos Aires,10000.00,SUV
1432,Chevrolet,1970,10547,Mocoretá,Corrientes,4064.52,Pickup
1727,Ford,1929,1000,Las Heras,Mendoza,19500.00,Clásico
1857,Ford,1974,59000,Juarez Celman,Córdoba,2774.19,Pickup
2145,FIAT,1963,250000,Villa Allende,Córdoba,1612.90,Clásico
2385,Chevrolet,1947,77000,Parana,Entre Ríos,30000.00,Sedán
2957,Peugeot,1978,3000,Palermo,Ciudad Autónoma Buenos Aires,4999.00,Clásico
2962,Chevrolet,1966,100000,Nuñez,Ciudad Autónoma Buenos Aires,11500.00,Pickup
3413,FIAT,1967,97000,Ensenada,Buenos Aires,1935.48,Clásico
3477,Renault,1975,100000,Guaymallén,Mendoza,1290.32,Clásico
3579,FIAT,1962,1000,Campana,Buenos Aires,10000.00,Hatchback
3822,Chevrolet,1965,12000,San Fernando,Buenos Aires (A.M.B.A.),7000.00,Pickup
3873,Peugeot,1974,250000,Quilmes Oeste,Buenos Aires (A.M.B.A.),4500.00,Clásico
3958,Ika,1970,1100,La Falda,Córdoba,10967.74,Clásico
3970,FIAT,1976,10000,Ciudad De San Martin,Mendoza,2903.23,Hatchback
4138,FIAT,1970,86000,Pila,Buenos Aires,4500.00,Clásico
4222,Renault,1974,10000,Pavón,Santa Fe,10000.00,Clásico
4353,Mercedes,1973,200000,Ituzaingo,Buenos Aires (A.M.B.A.),36000.00,Camión
4389,Ford,1966,500000,La Plata,Buenos Aires,5000.00,Pickup
4644,Ford,1966,36100,Barrio Belgrano,Buenos Aires,10000.00,Coupé

Estadisticas de las variables numericas listas

In [331]:
df.describe()

              anio             km    precio_usd
count  4614.000000    4614.000000   4614.000000
mean   2016.073906  114600.014088  12998.580065
std       6.811669   79836.704641   8844.681146
min    1929.000000       1.000000   1000.000000
25%    2013.000000   60000.000000   7419.350000
50%    2017.000000  105000.000000  10645.160000
75%    2020.000000  153000.000000  16000.000000
max    2026.000000  955000.000000  76900.000000

## Analisis de variables cualitativas

### Cardinalidad:

Cómo estan compuestas las columnas cualitativas? Resisten one hot encoding? (previamente a utilizar KNN Regressor, evalué utilizar Random Forest Rregressor)
En este caso 'marca' y 'provincia' podrian resisistilo y aportar informacion util al modelo y no solo ruido cuando existen demasiados registros con 0.

In [332]:
df.head(3)

,marca,anio,km,ciudad,provincia,precio_usd,carroceria
0,Chevrolet,2018,73000,Hurlingham,Buenos Aires (A.M.B.A.),6451.61,Hatchback
1,Chevrolet,2023,102000,Saavedra,Ciudad Autónoma Buenos Aires,16129.03,Hatchback
2,Citroën,2017,84000,Flores,Ciudad Autónoma Buenos Aires,10903.23,Minivan

* Cuantas filas tiene cada marca? 
* Cuales marcas aportan informacion y cuantas tienen tan pocos registros que no resultan significativas? 
* Cuantas marcas concentran el mayor porcentaje de registros? 
* cuales pueden ser agrupados como 'otro' ?

In [333]:
# frecuencias relativas acumuladas: 

df['marca'].value_counts(normalize=True).cumsum()

marca
Volkswagen    0.161032
Peugeot       0.313827
Ford          0.440182
Chevrolet     0.537278
Renault       0.634157
FIAT          0.724534
Toyota        0.800607
Citroën       0.847204
Nissan        0.875163
Honda         0.894885
Jeep          0.913524
Mercedes      0.926094
BMW           0.937365
Audi          0.948635
Hyundai       0.957304
Chery         0.965323
KIA           0.970741
Suzuki        0.974426
DS            0.977026
RAM           0.979627
Dodge         0.982011
Mitsubishi    0.983962
MINI          0.985696
Lifan         0.986996
BAIC          0.988080
Subaru        0.989163
Alfa Romeo    0.990247
Geely         0.991331
Volvo         0.992198
SEAT          0.993065
smart         0.993715
Foton         0.994365
Chrysler      0.995015
Daihatsu      0.995665
DFSK          0.996099
Zanella       0.996532
JAC           0.996966
MG            0.997399
Haval         0.997833
Iveco         0.998266
Porsche       0.998700
Agrale        0.998916
Isuzu         0.999133
SWM           0.999350
Shineray      0.999567
Great Wall    0.999783
Ika           1.000000
Name: proportion, dtype: float64

In [334]:
'''
import numpy as np
umbral = 0.95
frecuencias = df['marca'].value_counts(normalize=True)
top_marcas = frecuencias[frecuencias.cumsum() <= umbral].index

df['carroceria'] = np.where(df['categoria'] == 'coleccion',
                           df['categoria'],
                           df['marca'].where(df['marca'].isin(top_marcas), 'Otros')
                           )
'''

# esta lineas de codigo agrupaban todas las marcas con baja cantidad de registros dentro de 'otros', 
# el agrupamiento por marca unicamente no permitia que el modelo entienda la jerarquia entre vehiculos dentro
# de cada marca ej: Corolla o Hilux tienen precios distintos y el modelo solo veia Toyota.
# Posteriormente cree la clasificacion por carroceria para darle esta infomacion al modelo con una cantidad
# acotada de registros, en lugar de dejar la columna 'modelo' que aportaba  mas de 400 registros distintos
# de los cuales el modelo seleccionado no podia aprender

"\nimport numpy as np\numbral = 0.95\nfrecuencias = df['marca'].value_counts(normalize=True)\ntop_marcas = frecuencias[frecuencias.cumsum() <= umbral].index\n\ndf['carroceria'] = np.where(df['categoria'] == 'coleccion',\n                           df['categoria'],\n                           df['marca'].where(df['marca'].isin(top_marcas), 'Otros')\n                           )\n"

In [335]:
# en lugar de marca, estas son las columnas que debo encodear
df['carroceria'].unique()

<StringArray>
[ 'Hatchback',    'Minivan',     'Furgón',      'Sedán',        'SUV',
     'Pickup',    'Clásico',     'Camión',  'Cabriolet',      'Wagon',
      'Coupé', 'Utilitario']
Length: 12, dtype: str

In [336]:
import plotly.express as px

scatter_precio_categoria = px.scatter(df,
                                      x = 'carroceria',
                                      y = 'precio_usd',
                                      color = 'anio',
                                      template = 'plotly_dark',
                                      title = 'Distribucion de precios por categoria: carroceria',
                                      hover_data= 'marca')
scatter_precio_categoria.show()

### Impacto de la ubicacion geografica sobre los precios 
Analizando los valores de 'precios_usd', se observa que la mediana para todas las provincias es estable (entre 0-20k), pero si existen mayor cantidad de valores elevados y outlers en provincias marcadas.

Expandire el analisis con ANOVA, para determinar si la ubicacion geografica del vehiculo aporta informacion al modelo predictivo.

In [337]:
orden = df.groupby('provincia')['precio_usd'].median().sort_values(ascending=False).index

box = px.box(df,
             x = 'provincia',
             y = 'precio_usd',
             category_orders={'provincia': list(orden)},
             template = 'plotly_dark',
             hover_data='marca',
             ).show()

Analizando los rangos de precios por ciudad dentro de cada provincia, vemos que este tampoco esta determinado por la ubicacion.

In [338]:
prov_interes = ['Buenos Aires (A.M.B.A.)', 'Córdoba', 'Neuquén', 'Santa Cruz']

df_filtro = df[df['provincia'].isin(prov_interes)]

segmentacion_prov_ciud = (df[df['provincia'].isin(prov_interes)]
                          .groupby(['provincia','ciudad'])['precio_usd']
                          .median().sort_values(ascending=False))

orden_ciudades = segmentacion_prov_ciud.index.get_level_values('ciudad').tolist()

box = px.box(df_filtro,
             x = 'ciudad',
             y = 'precio_usd',
             color = 'provincia',
             category_orders={'ciudad': orden_ciudades},
             template = 'plotly_dark',
             hover_data='marca',
             ).show()

📊 ANOVA (Analysis of Variance)
Qué mide: compara las medias de una variable numérica entre distintos grupos categóricos.

La prueba ANOVA mostró diferencias estadísticamente significativas entre las medias de los grupos (F = 3.91, p < 0.001). Por lo tanto, se rechaza la hipótesis nula de igualdad de medias

In [339]:
from scipy import stats

# HO = el precio promedio es igual en todas las provincias? 

grupos = [df[df['provincia'] == p]['precio_usd'] for p in df['provincia'].unique()]
f_stat, p_val = stats.f_oneway(*grupos)

# Cociente entre "cuánto varían los promedios entre provincias" y 
# "cuánto varía el precio dentro de cada provincia
print("F-statistic:", f_stat)

# el precio promedio sí difiere significativamente entre provincias, no es casualidad.
print("p-value:", p_val)

F-statistic: 3.9104463599567834
p-value: 4.3525743602629964e-10

In [340]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

tukey = pairwise_tukeyhsd(endog=df['precio_usd'],
                          groups=df['provincia'],
                          alpha=0.05)

print(tukey)

                           Multiple Comparison of Means - Tukey HSD, FWER=0.05
=========================================================================================================
           group1                       group2             meandiff  p-adj     lower      upper    reject
---------------------------------------------------------------------------------------------------------
                Buenos Aires      Buenos Aires (A.M.B.A.)  -675.8321 0.9996  -2419.4939  1067.8298  False
                Buenos Aires                    Catamarca   524.2632    1.0 -15603.9883 16652.5148  False
                Buenos Aires                        Chaco -3281.1986 0.5056  -7666.9005  1104.5033  False
                Buenos Aires                       Chubut  -242.2894    1.0  -7749.8485  7265.2698  False
                Buenos Aires Ciudad Autónoma Buenos Aires -2501.5804    0.0  -4201.1502  -802.0105   True
                Buenos Aires                   Corrientes   607.0177    1.0  -4389.9579  5603.9933  False
                Buenos Aires                      Córdoba   -21.9055    1.0  -1981.3452  1937.5341  False
                Buenos Aires                   Entre Ríos  1699.9225 0.9904  -1844.4545  5244.2995  False
                Buenos Aires                      Formosa   796.8457    1.0 -15331.4058 16925.0973  False
                Buenos Aires                        Jujuy -2077.1182    1.0  -14304.527 10150.2906  False
                Buenos Aires                     La Pampa  2613.2585    1.0  -5308.5987 10535.1158  False
                Buenos Aires                     La Rioja   2492.007    1.0  -8956.7643 13940.7783  False
                Buenos Aires                      Mendoza -2120.0251 0.1291  -4434.8583   194.8081  False
                Buenos Aires                     Misiones  -637.9331    1.0  -4786.4422  3510.5761  False
                Buenos Aires                      Neuquén   2028.959 0.8772  -1324.5184  5382.4365  False
                Buenos Aires                    Río Negro -1496.4865    1.0  -6967.3271  3974.3541  False
                Buenos Aires                        Salta  1018.7798    1.0  -3743.1117  5780.6714  False
                Buenos Aires                     San Juan  -603.4251    1.0  -9987.4001  8780.5499  False
                Buenos Aires                     San Luis  -651.1889    1.0  -4912.5264  3610.1485  False
                Buenos Aires                   Santa Cruz  4861.3592    1.0  -9578.2406 19300.9591  False
                Buenos Aires                     Santa Fe    -626.23    1.0  -2972.3374  1719.8775  False
                Buenos Aires          Santiago del Estero -1837.0268    1.0 -16276.6266 12602.5731  False
                Buenos Aires             Tierra del Fuego -1360.8155    1.0 -12809.5868 10087.9558  False
                Buenos Aires                      Tucumán  -818.0888    1.0  -4582.8927  2946.7152  False
     Buenos Aires (A.M.B.A.)                    Catamarca  1200.0953    1.0 -14896.6247 17296.8153  False
     Buenos Aires (A.M.B.A.)                        Chaco -2605.3665 0.8675   -6873.654  1662.9209  False
     Buenos Aires (A.M.B.A.)                       Chubut   433.5427    1.0  -7006.0367   7873.122  False
     Buenos Aires (A.M.B.A.) Ciudad Autónoma Buenos Aires -1825.7483 0.0003  -3194.1174  -457.3792   True
     Buenos Aires (A.M.B.A.)                   Corrientes  1282.8497    1.0  -3611.3981  6177.0975  False
     Buenos Aires (A.M.B.A.)                      Córdoba   653.9265 0.9996  -1026.3414  2334.1945  False
     Buenos Aires (A.M.B.A.)                   Entre Ríos  2375.7546 0.6504  -1022.2603  5773.7694  False
     Buenos Aires (A.M.B.A.)                      Formosa  1472.6778    1.0 -14624.0422 17569.3978  False
     Buenos Aires (A.M.B.A.)                        Jujuy -1401.2861    1.0 -13587.0739 10784.5016  False
     Buenos Aires (A.M.B.A.)                     La Pampa  3289.0906 0.9986   -4568.372 11146.5532  False
     Buenos Aires (A.M.B.A.)                     La Rioja  3167.8391    1.0  -8236.4698 14572.1479  False
     Buenos Aires (A.M.B.A.)                      Mendoza  -1444.193 0.6679  -3528.0235   639.6374  False
     Buenos Aires (A.M.B.A.)                     Misiones     37.899    1.0   -3986.281   4062.079  False
     Buenos Aires (A.M.B.A.)                      Neuquén  2704.7911 0.2503   -493.6003  5903.1825  False
     Buenos Aires (A.M.B.A.)                    Río Negro  -820.6544    1.0  -6197.8278  4556.5189  False
     Buenos Aires (A.M.B.A.)                        Salta  1694.6119 0.9999  -2959.3658  6348.5896  False
     Buenos Aires (A.M.B.A.)                     San Juan     72.407    1.0  -9257.2706  9402.0845  False
     Buenos Aires (A.M.B.A.)                     San Luis    24.6431    1.0  -4115.7546  4165.0408  False
     Buenos Aires (A.M.B.A.)                   Santa Cruz  5537.1913 0.9996   -8867.181 19941.5636  False
     Buenos Aires (A.M.B.A.)                     Santa Fe    49.6021    1.0  -2068.9155  2168.1196  False
     Buenos Aires (A.M.B.A.)          Santiago del Estero -1161.1947    1.0  -15565.567 13243.1776  False
     Buenos Aires (A.M.B.A.)             Tierra del Fuego  -684.9834    1.0 -12089.2923 10719.3254  False
     Buenos Aires (A.M.B.A.)                      Tucumán  -142.2567    1.0  -3769.6035  3485.0901  False
                   Catamarca                        Chaco -3805.4618    1.0  -20397.581 12786.6574  False
                   Catamarca                       Chubut  -766.5526    1.0  -18442.171 16909.0657  False
                   Catamarca Ciudad Autónoma Buenos Aires -3025.8436    1.0 -19117.8471 13066.1599  False
                   Catamarca                   Corrientes    82.7544    1.0 -16681.3084 16846.8173  False
                   Catamarca                      Córdoba  -546.1688    1.0 -16667.6899 15575.3523  False
                   Catamarca                   Entre Ríos  1175.6593    1.0 -15214.1744 17565.4929  False
                   Catamarca                      Formosa   272.5825    1.0 -22447.1124 22992.2774  False
                   Catamarca                        Jujuy -2601.3814    1.0 -22740.2385 17537.4757  False
                   Catamarca                     La Pampa  2088.9953    1.0 -15766.5322 19944.5228  False
                   Catamarca                     La Rioja  1967.7438    1.0 -17708.0892 21643.5767  False
                   Catamarca                      Mendoza -2644.2883    1.0 -18812.8532 13524.2766  False
                   Catamarca                     Misiones -1162.1963    1.0 -17693.2025 15368.8099  False
                   Catamarca                      Neuquén  1504.6958    1.0 -14844.9173 17854.3089  False
                   Catamarca                    Río Negro -2020.7497    1.0 -18932.1109 14890.6114  False
                   Catamarca                        Salta   494.5166    1.0 -16200.9813 17190.0145  False
                   Catamarca                     San Juan -1127.6883    1.0 -19678.2416 17422.8649  False
                   Catamarca                     San Luis -1175.4522    1.0 -17735.1332 15384.2288  False
                   Catamarca                   Santa Cruz   4337.096    1.0 -17216.6991 25890.8911  False
                   Catamarca                     Santa Fe -1150.4932    1.0 -17323.5653 15022.5788  False
                   Catamarca          Santiago del Estero   -2361.29    1.0 -23915.0851 19192.5051  False
                   Catamarca             Tierra del Fuego -1885.0788    1.0 -21560.9117 17790.7542  False
                   Catamarca                      Tucumán  -1342.352    1.0 -17781.2628 15096.5588  False
                       Chaco                       Chubut  3038.9092 0.9999  -5419.3037 11497.1221  False
                       Chaco Ciudad Autónoma Buenos Aires   779.6182    1.0  -3470.8475  5030.0839  False
                       Chaco                   Corrientes  3888.2163 0.8614  -2448.0039 10224.4365  False
                       Chaco                      Córdoba  3259.2931 0.5079  -1101.5927  7620.1789  False
                       Chaco                   Entre Ríos  4981.1211 0.0939   -285.8068  10248.049  False
                       Chaco                      Formosa  4078.0443    1.0 -12514.0749 20670.1635  False
                       Chaco                        Jujuy  1204.0804    1.0 -11628.9803 14037.1411  False
                       Chaco                     La Pampa  5894.4571 0.7376  -2933.5519 14722.4662  False
                       Chaco                     La Rioja  5773.2056  0.991  -6320.2755 17866.6867  False
                       Chaco                      Mendoza  1161.1735    1.0  -3370.5341  5692.8811  False
                       Chaco                     Misiones  2643.2655 0.9937  -3047.7844  8334.3154  False
                       Chaco                      Neuquén  5310.1576  0.033    169.7557 10450.5596   True
                       Chaco                    Río Negro  1784.7121    1.0  -4931.5382  8500.9624  False
                       Chaco                        Salta  4299.9784 0.6511   -1852.544 10452.5009  False
                       Chaco                     San Juan  2677.7735    1.0   -7482.783   12838.33  False
                       Chaco                     San Luis  2630.0096 0.9952  -3143.8035  8403.8228  False
                       Chaco                   Santa Cruz  8142.5578 0.9561  -6813.3763  23098.492  False
                       Chaco                     Santa Fe  2654.9686 0.9112  -1892.7936  7202.7308  False
                       Chaco          Santiago del Estero  1444.1718    1.0 -13511.7623  16400.106  False
                       Chaco             Tierra del Fuego  1920.3831    1.0  -10173.098 14013.8642  False
                       Chaco                      Tucumán  2463.1098 0.9953  -2954.6083   7880.828  False
                      Chubut Ciudad Autónoma Buenos Aires  -2259.291    1.0  -9688.6599  5170.0779  False
                      Chubut                   Corrientes   849.3071    1.0  -7941.4124  9640.0266  False
                      Chubut                      Córdoba   220.3839    1.0  -7272.7055  7713.4732  False
                      Chubut                   Entre Ríos  1942.2119    1.0  -6111.9543  9996.3781  False
                      Chubut                      Formosa  1039.1351    1.0 -16636.4832 18714.7535  False
                      Chubut                        Jujuy -1834.8288    1.0 -16041.0426  12371.385  False
                      Chubut                     La Pampa  2855.5479    1.0  -7871.1854 13582.2812  False
                      Chubut                     La Rioja  2734.2964    1.0 -10807.5406 16276.1334  False
                      Chubut                      Mendoza -1877.7357    1.0  -9471.5119  5716.0405  False
                      Chubut                     Misiones  -395.6437    1.0   -8733.336  7942.0486  False
                      Chubut                      Neuquén  2271.2484    1.0  -5700.7523 10243.2492  False
                      Chubut                    Río Negro -1254.1971    1.0 -10322.6634  7814.2692  False
                      Chubut                        Salta  1261.0692    1.0  -7398.1799  9920.3184  False
                      Chubut                     San Juan  -361.1357    1.0 -12208.7503 11486.4789  False
                      Chubut                     San Luis  -408.8996    1.0  -8803.3013  7985.5022  False
                      Chubut                   Santa Cruz  5103.6486    1.0 -11045.9343 21253.2316  False
                      Chubut                     Santa Fe  -383.9406    1.0  -7987.3086  7219.4274  False
                      Chubut          Santiago del Estero -1594.7374    1.0 -17744.3203 14554.8456  False
                      Chubut             Tierra del Fuego -1118.5261    1.0 -14660.3631 12423.3109  False
                      Chubut                      Tucumán  -575.7994    1.0  -8729.3712  7577.7724  False
Ciudad Autónoma Buenos Aires                   Corrientes   3108.598 0.8125  -1770.1152  7987.3113  False
Ciudad Autónoma Buenos Aires                      Córdoba  2479.6748    0.0    845.2081  4114.1415   True
Ciudad Autónoma Buenos Aires                   Entre Ríos  4201.5029 0.0014    825.9013  7577.1044   True
Ciudad Autónoma Buenos Aires                      Formosa  3298.4261    1.0 -12793.5774 19390.4296  False
Ciudad Autónoma Buenos Aires                        Jujuy   424.4622    1.0 -11755.0946  12604.019  False
Ciudad Autónoma Buenos Aires                     La Pampa  5114.8389 0.7782   -2732.957 12962.6348  False
Ciudad Autónoma Buenos Aires                     La Rioja  4993.5873 0.9973  -6404.0634 16391.2381  False
Ciudad Autónoma Buenos Aires                      Mendoza   381.5553    1.0  -1665.5232  2428.6338  False
Ciudad Autónoma Buenos Aires                     Misiones  1863.6473 0.9936   -2141.625  5868.9195  False
Ciudad Autónoma Buenos Aires                      Neuquén  4530.5394 0.0001   1355.9704  7705.1084   True
Ciudad Autónoma Buenos Aires                    Río Negro  1005.0939    1.0  -4357.9439  6368.1317  False
Ciudad Autónoma Buenos Aires                        Salta  3520.3602 0.4736  -1117.2781  8157.9985  False
Ciudad Autónoma Buenos Aires                     San Juan  1898.1553    1.0  -7423.3824 11219.6929  False
Ciudad Autónoma Buenos Aires                     San Luis  1850.3914 0.9961  -2271.6317  5972.4145  False
Ciudad Autónoma Buenos Aires                   Santa Cruz  7362.9396 0.9785  -7036.1618  21762.041  False
Ciudad Autónoma Buenos Aires                     Santa Fe  1875.3504 0.1507   -207.0275  3957.7283  False
Ciudad Autónoma Buenos Aires          Santiago del Estero   664.5536    1.0 -13734.5478  15063.655  False
Ciudad Autónoma Buenos Aires             Tierra del Fuego  1140.7648    1.0 -10256.8859 12538.4156  False
Ciudad Autónoma Buenos Aires                      Tucumán  1683.4916 0.9933  -1922.8675  5289.8507  False
                  Corrientes                      Córdoba  -628.9232    1.0  -5604.1326  4346.2862  False
                  Corrientes                   Entre Ríos  1092.9048    1.0  -4692.9325  6878.7421  False
                  Corrientes                      Formosa   189.8281    1.0 -16574.2348 16953.8909  False
                  Corrientes                        Jujuy -2684.1359    1.0 -15738.7455 10370.4737  False
                  Corrientes                     La Pampa  2006.2408    1.0  -7140.8422 11153.3239  False
                  Corrientes                     La Rioja  1884.9893    1.0 -10443.3386 14213.3172  False
                  Corrientes                      Mendoza -2727.0428  0.966  -7852.6411  2398.5555  False
                  Corrientes                     Misiones -1244.9508    1.0  -7419.3684  4929.4669  False
                  Corrientes                      Neuquén  1421.9414    1.0  -4248.9595  7092.8422  False
                  Corrientes                    Río Negro -2103.5042    1.0  -9233.9601  5026.9518  False
                  Corrientes                        Salta   411.7622    1.0  -6190.4281  7013.9524  False
                  Corrientes                     San Juan -1210.4428    1.0 -11649.4222  9228.5366  False
                  Corrientes                     San Luis -1258.2066    1.0  -7508.9907  4992.5775  False
                  Corrientes                   Santa Cruz  4254.3416    1.0 -10892.1217 19400.8048  False
                  Corrientes                     Santa Fe -1233.2477    1.0  -6373.0458  3906.5505  False
                  Corrientes          Santiago del Estero -2444.0444    1.0 -17590.5077 12702.4188  False
                  Corrientes             Tierra del Fuego -1967.8332    1.0 -14296.1611 10360.4947  False
                  Corrientes                      Tucumán -1425.1064    1.0   -7348.539  4498.3261  False
                     Córdoba                   Entre Ríos  1721.8281 0.9873  -1791.7957  5235.4518  False
                     Córdoba                      Formosa   818.7513    1.0 -15302.7698 16940.2724  False
                     Córdoba                        Jujuy -2055.2127    1.0 -14273.7424 10163.3171  False
                     Córdoba                     La Pampa  2635.1641    1.0  -5272.9815 10543.3096  False
                     Córdoba                     La Rioja  2513.9125    1.0  -8925.3754 13953.2004  False
                     Córdoba                      Mendoza -2098.1196  0.117  -4365.5844   169.3453  False
                     Córdoba                     Misiones  -616.0276    1.0  -4738.2929  3506.2378  False
                     Córdoba                      Neuquén  2050.8646 0.8538  -1270.0923  5371.8215  False
                     Córdoba                    Río Negro  -1474.581    1.0  -6925.5479   3976.386  False
                     Córdoba                        Salta  1040.6854    1.0  -3698.3605  5779.7312  False
                     Córdoba                     San Juan  -581.5196    1.0  -9953.9221   8790.883  False
                     Córdoba                     San Luis  -629.2834    1.0  -4865.0762  3606.5094  False
                     Córdoba                   Santa Cruz  4883.2648    1.0  -9548.8172 19315.3467  False
                     Córdoba                     Santa Fe  -604.3245    1.0  -2903.7078  1695.0589  False
                     Córdoba          Santiago del Estero -1815.1212    1.0 -16247.2032 12616.9607  False
                     Córdoba             Tierra del Fuego   -1338.91    1.0 -12778.1979 10100.3779  False
                     Córdoba                      Tucumán  -796.1832    1.0  -4532.0489  2939.6824  False
                  Entre Ríos                      Formosa  -903.0768    1.0 -17292.9104 15486.7569  False
                  Entre Ríos                        Jujuy -3777.0407    1.0 -16347.4693  8793.3879  False
                  Entre Ríos                     La Pampa    913.336    1.0  -7528.3446  9355.0166  False
                  Entre Ríos                     La Rioja   792.0845    1.0 -11022.3352 12606.5042  False
                  Entre Ríos                      Mendoza -3819.9476 0.0362  -7543.4676   -96.4276   True
                  Entre Ríos                     Misiones -2337.8556 0.9944  -7408.9774  2733.2662  False
                  Entre Ríos                      Neuquén   329.0365    1.0  -4115.2811  4773.3542  False
                  Entre Ríos                    Río Negro  -3196.409 0.9763  -9396.1062  3003.2882  False
                  Entre Ríos                        Salta  -681.1427    1.0  -6265.2057  4902.9203  False
                  Entre Ríos                     San Juan -2303.3476    1.0 -12130.1037  7523.4084  False
                  Entre Ríos                     San Luis -2351.1115 0.9952  -7514.9419   2812.719  False
                  Entre Ríos                   Santa Cruz  3161.4367    1.0 -11569.7612 17892.6347  False
                  Entre Ríos                     Santa Fe -2326.1525 0.8461  -6069.1952  1416.8902  False
                  Entre Ríos          Santiago del Estero -3536.9493    1.0 -18268.1472 11194.2487  False
                  Entre Ríos             Tierra del Fuego  -3060.738    1.0 -14875.1577  8753.6817  False
                  Entre Ríos                      Tucumán -2518.0113 0.9683  -7280.3528  2244.3302  False
                     Formosa                        Jujuy -2873.9639    1.0  -23012.821 17264.8932  False
                     Formosa                     La Pampa  1816.4128    1.0 -16039.1147 19671.9403  False
                     Formosa                     La Rioja  1695.1613    1.0 -17980.6717 21370.9942  False
                     Formosa                      Mendoza -2916.8708    1.0 -19085.4357 13251.6941  False

La localidad parece estar asociada al precio, pero eso no significa necesariamente que la localidad sea la causa de que el vehículo tenga ese precio

con el analisis ANOVA encontré diferencias significativas entre provincias, pero el Tukey mostró que esas diferencias están concentradas en unos pocos pares y no son generalizadas entre todas las provincias.

Eso me permite plantear la siguiente hipotesis:

Provincia → puede estar capturando diferencias de composición del mercado, pero no necesariamente un efecto propio de la provincia

La variable provincia puede actuar como una variable proxy de la composición del mercado. Las diferencias observadas en el precio promedio entre provincias podrían estar explicadas, al menos parcialmente, por las características de los vehículos disponibles en cada una, como marca, modelo, año, kilometraje o segmento, en lugar de representar un efecto intrínseco de la provincia.

Quitaré la columna de ciudad, conservo solamente provincia pero estará sujeta su conservacion a las pruebas de entrenamiento segun el aporte que haga o no en RMSE, MAE y R²

In [341]:
df= df.drop(columns='ciudad')

Reemplazo la columna de anio por 'antiguedad'

In [342]:
df['antiguedad'] = 2026 - df['anio']
df.drop(columns='anio', inplace=True)
df.head(3)

,marca,km,provincia,precio_usd,carroceria,antiguedad
0,Chevrolet,73000,Buenos Aires (A.M.B.A.),6451.61,Hatchback,8
1,Chevrolet,102000,Ciudad Autónoma Buenos Aires,16129.03,Hatchback,3
2,Citroën,84000,Ciudad Autónoma Buenos Aires,10903.23,Minivan,9

In [343]:
# correlacion de las variables numericas

df_corr = df[['km','precio_usd', 'antiguedad']]

matriz_corr = df_corr.corr(method='spearman') # la relación no es lineal pero sí monotónica 
print(matriz_corr)

                  km  precio_usd  antiguedad
km          1.000000   -0.239048    0.708473
precio_usd -0.239048    1.000000   -0.427211
antiguedad  0.708473   -0.427211    1.000000

* km ↔ antigüedad: 0.72 → relación positiva fuerte (a mayor antigüedad, más km).

* precio_usd ↔ antigüedad: -0.43 → relación negativa moderada (autos más viejos tienden a valer menos).

* precio_usd ↔ km: -0.25 → relación negativa débil (más km suele bajar el precio, pero no tan marcado).

# Encoding KNN

KNN mide distancias entre autos. Sin escalar, km (que llega a cientos de miles) aplastaría a las demás columnas en esa distancia. StandardScaler deja todas las columnas en una escala comparable (media 0, desvío 1). fit_transform en train (aprende la escala y la aplica); transform en test (aplica la misma escala aprendida, sin volver a aprenderla).

In [344]:
df_encoded = df.copy()

In [345]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

X = df_encoded[['km','marca','provincia', 'carroceria', 'antiguedad']]
y = df_encoded['precio_usd']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [346]:
# 2. Encoding calculado SOLO con y_train
media_provincia = y_train.groupby(X_train['provincia']).mean()
media_carroceria = y_train.groupby(X_train['carroceria']).mean()
media_marca = y_train.groupby(X_train['marca']).mean()

In [347]:
X_train = X_train.copy()
X_test = X_test.copy()

In [348]:
media_global = y_train.mean()
X_train['provincia_enc'] = X_train['provincia'].map(media_provincia)
X_test['provincia_enc']  = X_test['provincia'].map(media_provincia)
X_train['carroceria_enc'] = X_train['carroceria'].map(media_categoria)
X_test['carroceria_enc']  = X_test['carroceria'].map(media_categoria)
X_train['marca_enc'] = X_train['marca'].map(media_marca).fillna(media_global)
X_test['marca_enc']  = X_test['marca'].map(media_marca).fillna(media_global)

In [349]:
X_train

,km,marca,provincia,carroceria,antiguedad,provincia_enc,carroceria_enc,marca_enc
1523,65000,Chevrolet,Córdoba,Hatchback,5,13815.218380,9387.206360,11098.461853
1490,150000,Chevrolet,Buenos Aires,SUV,10,13627.031060,17454.984524,11098.461853
1492,90000,Volkswagen,Ciudad Autónoma Buenos Aires,SUV,4,11585.123734,17454.984524,11248.164226
2780,175000,Volkswagen,Mendoza,Hatchback,20,11744.128125,9387.206360,11248.164226
1908,23000,Ford,Buenos Aires (A.M.B.A.),Pickup,3,13306.518662,19547.940855,13371.772026
...,...,...,...,...,...,...,...,...
4459,156000,Volkswagen,Ciudad Autónoma Buenos Aires,Minivan,16,11585.123734,9546.655101,11248.164226
473,121000,Citroën,Mendoza,SUV,11,11744.128125,17454.984524,9998.325988
3117,90000,Ford,Buenos Aires (A.M.B.A.),Pickup,4,13306.518662,19547.940855,13371.772026
3800,189000,FIAT,Buenos Aires,Furgón,14,13627.031060,13230.319722,9991.715074
869,17500,Volkswagen,Ciudad Autónoma Buenos Aires,Pickup,2,11585.123734,19547.940855,11248.164226

In [350]:
# X_train.head()
X_train = X_train.drop(columns=['provincia', 'carroceria','marca'])
X_test  = X_test.drop(columns=['provincia', 'carroceria', 'marca'])

In [351]:
import category_encoders as ce
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
import numpy as np

In [352]:
# 3. Escalado (ahora sí, fit solo en train)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# Baseline KNN

KNN Baseline (SIN MARCA)
----------------
* MAE: 4480.399336944745
* RMSE: 7007.986020245863
* R²: 0.3950399562051433
-----------------
KNN Baseline (CON MARCA ENCODED)
----------------
* MAE: 3370.1328689057423
* RMSE: 5643.469719725168
* R²: 0.6076870572276154

In [353]:
# ¿cuántos NaN hay y en qué columna?
X_test.isna().sum()

km                0
antiguedad        0
provincia_enc     0
carroceria_enc    0
marca_enc         0
dtype: int64

In [354]:
# Baseline valores de metricas sin ajustar ningun hiperparametros

knn = KNeighborsRegressor(n_neighbors=5)

knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("KNN Baseline")
print("----------------")
print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

KNN Baseline
----------------
MAE: 3370.1328689057423
RMSE: 5643.469719725168
R²: 0.6076870572276154

k = cantidad de registros vecinos que se usan para la prediccion

MAE = Error absoluto promedio ¿ cuanto se equivoca el modelo ? 

RMSE = Raiz cuadrada del error elevado al cuadrado. Penaliza los errores mas grandes. 

* Si MAE similar a RMSE, el modelo no tiene valores de error uniformes
* Si MAE << RMSE existen errores grandes

R2 = ¿Qué proporción de la variabilidad de mi variable objetivo consigue explicar el modelo?

In [355]:
import plotly.express as px 

mae = mean_absolute_error(y_test, y_pred)

scatter_base = px.scatter(x = y_test,
                     y = y_pred,
                     labels = {'x':'Precio Real', 'y':'Precio Predicho'},
                     title = 'Valor real versus valor predicho - BASELINE',
                     template = 'plotly_dark')

minimo = min(y_test.min(), y_pred.min())
maximo = max(y_test.max(), y_pred.max())

scatter_base.add_shape(type='line',
                     x0=minimo, y0=minimo,
                     x1=maximo, y1=maximo,
                     line=dict(color='red', dash='dash'))

scatter_base.show()

In [356]:
# Buscar mejor n_neighbors 

resultados_k = []

for k in range(1, 40):

    knn = KNeighborsRegressor(
        n_neighbors = k
    )

    knn.fit(X_train_scaled, y_train)

    y_pred = knn.predict(X_test_scaled)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    resultados_k.append({
        "k": k,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2
    })

import pandas as pd

df_k = pd.DataFrame(resultados_k)

mejor_k_rmse = df_k.loc[df_k["RMSE"].idxmin()]

print("Mejor K según RMSE:")
print(mejor_k_rmse)

Mejor K según RMSE:
k         13.000000
MAE     3274.893121
RMSE    5438.939731
R2         0.635608
Name: 12, dtype: float64

In [357]:
# weights = "distance"
'''
resultados_weights = []

for weight in ["uniform", "distance"]:

    knn = KNeighborsRegressor(
        n_neighbors = 33,   # ya con el valor de k obtenido en la prueba anterior 
        weights = weight    # uniform, 3805.696475, 6077.694781, 0.533536
    )

    knn.fit(X_train_scaled, y_train)

    y_pred = knn.predict(X_test_scaled)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    resultados_weights.append({
        "weights": weight,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2
    })
display(resultados_weights)
'''
import numpy as np
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

def evaluar_modelo(y_real, y_pred):

    mae = mean_absolute_error(y_real, y_pred)

    mse = mean_squared_error(y_real, y_pred)

    rmse = np.sqrt(mse)

    r2 = r2_score(y_real, y_pred)

    print(f"MAE:  {mae:.4f}")
    print(f"MSE:  {mse:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"R²:   {r2:.4f}")


knn = KNeighborsRegressor(
    n_neighbors = 13,
    weights = "distance",
    p = 2)

knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)

evaluar_modelo(y_test, y_pred)

MAE:  3247.8281
MSE:  30137244.4660
RMSE: 5489.7399
R²:   0.6288

In [358]:
import plotly.express as px 

scatter_p = px.scatter(x = y_test,
                     y = y_pred,
                     labels = {'x':'Precio Real', 'y':'Precio Predicho'},
                     title = 'Valor real versus valor predicho, FEATURES ✅ ',
                     template = 'plotly_dark')

minimo = min(y_test.min(), y_pred.min())
maximo = max(y_test.max(), y_pred.max())

scatter_p.add_shape(type='line',
                     x0=minimo, y0=minimo,
                     x1=maximo, y1=maximo,
                     line=dict(color='red', dash='dash'))

scatter_p.show()

In [303]:
import joblib
import os
print(os.getcwd())

carpeta_destino = 'g:\Mi unidad\Price_pred'

joblib.dump(knn, os.path.join(carpeta_destino,"knn_model.pkl"))
joblib.dump(scaler, os.path.join(carpeta_destino,"scaler.pkl"))

print("Modelo y scaler guardados correctamente.")

g:\Mi unidad\Price_pred\notebooks
Modelo y scaler guardados correctamente.

<>:5: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:5: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\soljo\AppData\Local\Temp\ipykernel_16536\1674369564.py:5: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  carpeta_destino = 'g:\Mi unidad\Price_pred'

In [359]:
import os
import joblib

artefactos = {
    'modelo': knn,
    'scaler': scaler,
    'media_provincia': media_provincia,
    'media_marca': media_marca,
    'media_carroceria': media_carroceria, 
    'columnas': X_train.columns.tolist(),
    'media_global': y_train.mean(),
}

carpeta_destino = r"G:\Mi unidad\Price_pred"
joblib.dump(artefactos, os.path.join(carpeta_destino, 'modelo_predictor.pkl'))

print("Modelo guardado correctamente.")

Modelo guardado correctamente.